### Registrar una foto nueva
POST http://localhost:8081/api/v1/photos/register
Content-Type: application/json

{
  "userId": "david_pro",
  "deviceModel": "Samsung S24 Ultra",
  "latitude": 41.3879,
  "longitude": 2.1699
}